export const theme = {
  primary: '#6B5CE7',
  primaryLight: '#EDE9FC',
  primaryDark: '#5A4BD6',
  secondary: '#F2A154',
  secondaryLight: '#FDF0E2',
  surface: '#FBF8F4',
  surfaceCard: '#FFFFFF',
  textPrimary: '#2D2A3E',
  textSecondary: '#8E8A9D',
  success: '#4CAF82',
  danger: '#E5544B',
  border: '#E8E4EF',
  onPrimary: '#FFFFFF',
  onSecondary: '#3D2200',
  shadow: 'rgba(45, 42, 62, 0.06)',
  overlay: 'rgba(45, 42, 62, 0.4)',
  online: '#4CAF82',
  tagBg: '#F3F0FA',
  tagText: '#6B5CE7',

  // Deprecated aliases — keep old components compiling until they migrate
  /** @deprecated use surface */ bg: '#FBF8F4',
  /** @deprecated use surfaceCard */ panel: '#FFFFFF',
  /** @deprecated use surface */ panelSoft: '#FBF8F4',
  /** @deprecated use surface */ panelMute: '#F5F2EE',
  /** @deprecated use textPrimary */ textMain: '#2D2A3E',
  /** @deprecated use textSecondary */ textSub: '#8E8A9D',
  /** @deprecated use textSecondary */ textDim: '#8E8A9D',
  /** @deprecated use secondary */ accent: '#F2A154',
  /** @deprecated use secondary */ accentStrong: '#F2A154',
  /** @deprecated use primary */ accentCool: '#6B5CE7',
} as const;
